version: "3.2"
services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    volumes:
      - '$HOME/neo4j/data:/data'
      - './neo4j/conf/:/conf/'
      - './neo4j/plugins/:/var/lib/neo4j/plugins/'
    environment:
      - NEO4JLABS_PLUGINS='["gds"]'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    networks: 
        - neo4j_go_net
    command: neo4j
  backend:
    container_name: 'api-go'
    build: '.'
    ports:
      - '3000:3000'
    volumes: 
      - '.:/go/src/app'
    depends_on: 
      - 'neo4j'
    networks: 
        - neo4j_go_net

networks:
  neo4j_go_net:
    driver: bridge

volumes:
  dgraph:

